name: take_note
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.1 
  json_annotation: ^4.9.0 
  flutter_screenutil: ^5.9.0 
  easy_date_timeline: ^2.0.9 
  intl: ^0.20.2 
  entry: ^1.0.0 
  confetti: 0.8.0 
  get: ^4.6.5
  shared_preferences: ^2.5.3 
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
